[package]
name = 'calculator_l12'
version = '1.0.0'

[dependencies]
AptosFramework = { local = "/Users/zhangwei/Documents/GitHub/aptos-core-main/aptos-move/framework/aptos-framework"}

[addresses]
metaschool = "0xa767004afbb9be8126297943626ee35355e630ec407715e1322572a625f0d1b5"
std = "0x1"